### ISSUE TITLE
Give us a build

### ISSUE THREAD

**Issue by notndricim** [CreeperG16/join-latest#1]

**Comment by theaddonn** [comment]
why would we?

**Comment by notndricim** [comment]
I dont really know how to build it myself so it would be helpful if we had one.

**Comment by FrederoxDev** [comment]
That's not how things work, if it was ready, there would be a build

**Comment by notndricim** [comment]
Oh thought this was already working. Sorry

**Comment by FrederoxDev** [comment]
no worries
